# Generated by Django 5.1.1 on 2024-11-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relations_books',
            name='status',
        ),
    ]
