# Generated by Django 5.1.1 on 2024-11-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relations',
            field=models.ManyToManyField(through='bookshop.Relations_books', to='bookshop.books'),
        ),
    ]
