# Generated by Django 5.1.1 on 2024-11-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_user_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='type',
            field=models.CharField(choices=[('pre-order', 'Предзаказ'), ('purchase', 'Покупка'), ('waiting', 'Ожидание'), ('rejected', 'Отклонена')], null=True, verbose_name='Тип покупки'),
        ),
    ]
