# Generated by Django 5.1.1 on 2024-10-04 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='company_id',
            new_name='company',
        ),
    ]
