# Generated by Django 5.1.1 on 2024-11-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0003_alter_purchases_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Полная стоимость'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='type',
            field=models.CharField(choices=[('purchase', 'Покупка'), ('waiting', 'Ожидание'), ('rejected', 'Отклонена')], null=True, verbose_name='Тип покупки'),
        ),
    ]
