# Generated by Django 5.1.1 on 2024-11-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_purchases_total_alter_purchases_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='books',
            field=models.ManyToManyField(related_name='purchases', to='bookshop.books', verbose_name='Позиции покупки'),
        ),
    ]
