# Generated by Django 5.1.1 on 2024-12-01 12:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_alter_purchases_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Оценка'),
        ),
    ]
