# Generated by Django 5.1.1 on 2024-10-04 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0006_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата отправки')),
                ('parent_message', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bookshop.support_messages', verbose_name='Ответ на')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
    ]
