# Generated by Django 5.1.1 on 2024-10-04 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0007_support_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_messages',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bookshop.support_messages', verbose_name='Ответ на'),
        ),
    ]
