# Generated by Django 5.1.1 on 2024-10-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_alter_support_messages_parent_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='support_messages',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
