# Generated by Django 5.1.1 on 2024-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_alter_support_messages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
