# Generated by Django 5.1.1 on 2024-10-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0011_books_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
