# Generated by Django 5.1.1 on 2024-10-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0012_books_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='cover',
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
