# Generated by Django 5.1.1 on 2024-10-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0013_remove_books_cover_alter_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.URLField(blank=True, max_length=128, unique=True, verbose_name='Ссылка на файл с книгой'),
        ),
    ]
