# Generated by Django 5.1.1 on 2024-10-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0014_alter_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.TextField(verbose_name='Ссылка на файл с книгой'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Название'),
        ),
    ]
