# Generated by Django 5.1.1 on 2024-10-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0015_alter_books_file_alter_books_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.BinaryField(verbose_name='Ссылка на файл с книгой'),
        ),
    ]
