# Generated by Django 5.1.1 on 2024-10-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0016_alter_books_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.TextField(verbose_name='Ссылка на файл с книгой'),
        ),
    ]
