# Generated by Django 5.1.1 on 2024-10-13 14:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0017_alter_books_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='age_limit',
            field=models.CharField(choices=[('zero', '0+'), ('six', '6+'), ('twelve', '12+'), ('sixteen', '16+'), ('eighteen', '18+')], default='zero', verbose_name='Возрастное ограничение'),
        ),
        migrations.AddField(
            model_name='books',
            name='author_mark',
            field=models.CharField(null=True, verbose_name='Авторский знак'),
        ),
        migrations.AddField(
            model_name='books',
            name='bbk',
            field=models.CharField(null=True, verbose_name='ББК'),
        ),
        migrations.AddField(
            model_name='books',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='bookshop.companies', verbose_name='Издательство'),
        ),
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.TextField(null=True, verbose_name='Файл с обложкой'),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.CharField(null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='books',
            name='priority',
            field=models.DecimalField(decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('10'))], verbose_name='Приоритет отображения'),
        ),
        migrations.AddField(
            model_name='books',
            name='publication_date',
            field=models.DateField(null=True, verbose_name='Дата публикации'),
        ),
        migrations.AddField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('released', 'Выпущена'), ('blocked', 'Заблокирована'), ('coming soon', 'Анонс'), ('request', 'Заявка')], default='request', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='books',
            name='udk',
            field=models.CharField(null=True, verbose_name='УДК'),
        ),
        migrations.AlterField(
            model_name='books',
            name='file',
            field=models.TextField(null=True, verbose_name='Файл с книгой'),
        ),
    ]
