# Generated by Django 5.1.1 on 2024-10-15 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0018_books_age_limit_books_author_mark_books_bbk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Имя')),
                ('b_day', models.DateField(blank=True, verbose_name='Дата рождения')),
                ('info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('books', models.ManyToManyField(to='bookshop.books')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_a',
            field=models.ManyToManyField(to='bookshop.authors'),
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Имя')),
                ('books', models.ManyToManyField(to='bookshop.books')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_g',
            field=models.ManyToManyField(to='bookshop.genres'),
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Имя')),
                ('genres', models.ManyToManyField(to='bookshop.genres')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Время совершения покупки')),
                ('type', models.CharField(choices=[('pre-order', 'Предзаказ'), ('purchase', 'Покупка')], null=True, verbose_name='Тип покупки')),
                ('books', models.ManyToManyField(to='bookshop.books', verbose_name='Позиции покупки')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
