# Generated by Django 5.1.1 on 2024-10-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0020_relations_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations_books',
            name='status',
            field=models.CharField(choices=[('selected', 'Выбрано'), ('not_selected', 'Не выбрано'), ('read', 'Прочитано'), ('reading', 'Читаю')], default='not_selected', verbose_name='Статус'),
        ),
    ]
