# Generated by Django 5.1.1 on 2024-10-17 18:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0021_alter_relations_books_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Оценка')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Время публикации')),
                ('type', models.CharField(choices=[('feedback', 'Отзыв'), ('complaint', 'Жалоба')], default='feedback', verbose_name='Тип')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to='bookshop.comments', verbose_name='Ответ на')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_Authors',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='c_author', serialize=False, to='bookshop.comments')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_author', to='bookshop.authors', verbose_name='Отзыв на автора')),
            ],
        ),
        migrations.CreateModel(
            name='Comments_Books',
            fields=[
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='comment_book', serialize=False, to='bookshop.comments')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_book', to='bookshop.books', verbose_name='Отзыв на книгу')),
            ],
        ),
    ]
