# Generated by Django 5.1.1 on 2024-10-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0022_comments_comments_authors_comments_books'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Список авторов'},
        ),
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Список книг'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Отзыв или жалоба', 'verbose_name_plural': 'Отзывы и жалобы'},
        ),
        migrations.AlterModelOptions(
            name='comments_authors',
            options={'verbose_name': 'Отзыв или жалоба на автора', 'verbose_name_plural': 'Отзывы или жалобы на автора'},
        ),
        migrations.AlterModelOptions(
            name='comments_books',
            options={'verbose_name': 'Отзыв или жалоба на книгу', 'verbose_name_plural': 'Отзывы и жалобы на книги'},
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Жанр или тег', 'verbose_name_plural': 'Жанры и теги'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Жанр или тег', 'verbose_name_plural': 'Жанры и теги'},
        ),
        migrations.AlterModelOptions(
            name='relations_books',
            options={'verbose_name': 'Связь с книгой', 'verbose_name_plural': 'Связи с книгами'},
        ),
    ]
