# Generated by Django 5.1.1 on 2024-10-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0023_alter_authors_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='books',
        ),
        migrations.RemoveField(
            model_name='genres',
            name='books',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='genres',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(to='bookshop.authors'),
        ),
        migrations.AddField(
            model_name='books',
            name='genres',
            field=models.ManyToManyField(to='bookshop.genres'),
        ),
        migrations.AddField(
            model_name='genres',
            name='groups',
            field=models.ManyToManyField(to='bookshop.groups'),
        ),
    ]
