# Generated by Django 5.1.1 on 2024-10-20 10:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0024_remove_authors_books_remove_genres_books_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупка'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1')), django.core.validators.MaxValueValidator(Decimal('5'))], verbose_name='Оценка'),
        ),
        migrations.CreateModel(
            name='ConfirmEmailKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, null=True, verbose_name='Ключ подтверждения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ключ подтвердения',
                'verbose_name_plural': 'Ключи подтверждения',
            },
        ),
    ]
