# Generated by Django 5.1.1 on 2024-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0026_alter_confirmemailkey_options_alter_genres_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('request', 'Заявка')], default='request', verbose_name='Статус'),
        ),
    ]
