# Generated by Django 5.1.1 on 2024-11-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0027_authors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.CharField(choices=[('released', 'Выпущена'), ('blocked', 'Заблокирована'), ('coming soon', 'Анонс'), ('request', 'Заявка'), ('rejected', 'Отклонена')], default='request', verbose_name='Статус'),
        ),
    ]
