# Generated by Django 5.1.1 on 2024-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0028_alter_books_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='books',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
    ]
