# Generated by Django 5.1.1 on 2024-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0029_authors_reason_books_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Активен'), ('request', 'Заявка')], default='request', verbose_name='Статус'),
        ),
    ]
