# Generated by Django 5.1.1 on 2024-11-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0030_alter_authors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='b_day',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='info',
            field=models.TextField(null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('request', 'Заявка')], default='request', verbose_name='Статус'),
        ),
    ]
