# Generated by Django 5.1.1 on 2024-11-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0031_alter_authors_b_day_alter_authors_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('request', 'Заявка'), ('rejected', 'Отклонен')], default='request', verbose_name='Статус'),
        ),
    ]
