# Generated by Django 5.1.1 on 2024-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0032_alter_authors_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('request', 'Заявка'), ('rejected', 'Отклонен'), ('blocked', 'Заблокирован')], default='request', verbose_name='Статус'),
        ),
    ]
