# Generated by Django 5.1.1 on 2024-11-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0034_alter_companies_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='status',
            field=models.CharField(choices=[('self-publishing', 'Самиздат'), ('publishing house', 'Издательство')], default='self-publishing', verbose_name='Статус'),
        ),
    ]
