# Generated by Django 5.1.1 on 2024-11-10 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0035_alter_companies_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support_messages',
            name='parent_message',
        ),
        migrations.AddField(
            model_name='support_messages',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='response', to=settings.AUTH_USER_MODEL, verbose_name='Владелец чата'),
        ),
    ]
