# Generated by Django 5.1.1 on 2024-11-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0037_comments_text_alter_support_messages_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_books',
            old_name='parent',
            new_name='book',
        ),
    ]
