# Generated by Django 5.1.1 on 2024-11-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0038_rename_parent_comments_books_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments_authors',
            old_name='parent',
            new_name='author',
        ),
    ]
